name: Conditional Build on [build] commit

on:
  push:
    branches: [ main ]

jobs:
  buildWindows:
    if: contains(github.event.head_commit.message, '[build]')
    name: Windows-64 Bit
    runs-on: windows-latest
    
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.0.40f1
          targetPlatform: StandaloneWindows64
          projectPath: Castawild

      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: build
